### ISSUE TITLE
delete these repos

### ISSUE THREAD

**Issue by VillainsRule4000** [qaiik/appetite#1]
I made a list of your blank repos (due to boredom).
https://github.com/qaiik/3kh0.github.io
https://github.com/qaiik/tyl
https://github.com/qaiik/base
https://github.com/qaiik/bob
https://github.com/qaiik/pngn
https://github.com/qaiik/wadec 
https://github.com/qaiik/watparse 
https://github.com/qaiik/3m-go
https://github.com/qaiik/gopoc
https://github.com/qaiik/rawhttpxclient
https://github.com/qaiik/easyjson
https://github.com/qaiik/hache
https://github.com/qaiik/eaz
https://github.com/qaiik/http.site
https://github.com/qaiik/screere
https://github.com/qaiik/blookethackingguide
https://github.com/qaiik/express-api-structure
https://github.com/qaiik/betastarapidocs
https://github.com/qaiik/xtotic
https://github.com/qaiik/autobookmark
https://github.com/qaiik/radaru
https://github.com/qaiik/discad
https://github.com/qaiik/readme
https://github.com/qaiik/svgui
https://github.com/qaiik/imonthenightshift
https://github.com/qaiik/passchex
https://github.com/qaiik/LookAtMeSpu7Nix
https://github.com/qaiik/mitm-gdps
https://github.com/qaiik/bim-js
https://github.com/qaiik/My-Altt
https://github.com/qaiik/blkt-hacking-guide
https://github.com/qaiik/2bloc
https://github.com/qaiik/mpi
https://github.com/qaiik/inner
https://github.com/qaiik/funkin
https://github.com/qaiik/antiware
https://github.com/qaiik/tsundle
https://github.com/qaiik/stock-over-flow
https://github.com/qaiik/dsadsa
https://github.com/qaiik/registra

**Comment by qaiik** [comment]
LOL thanks?

**Comment by qaiik** [comment]
actually tysm

**Comment by VillainsRule4000** [comment]
i was so bored

**Comment by VillainsRule4000** [comment]
bro's repo count went down by like 30 💀
